[package]
name = "pcm-extract"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wav = "1.0.0"
clap = "2.33.3"
env_logger = "0.8.1"
log = "0.4.11"
